// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// cpp11bigwig.cpp
writable::list read_bigwig_cpp(std::string bwfname, strings chroms_r, integers starts_r, integers ends_r);
extern "C" SEXP _cpp11bigwig_read_bigwig_cpp(SEXP bwfname, SEXP chroms_r, SEXP starts_r, SEXP ends_r) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_bigwig_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(bwfname), cpp11::as_cpp<cpp11::decay_t<strings>>(chroms_r), cpp11::as_cpp<cpp11::decay_t<integers>>(starts_r), cpp11::as_cpp<cpp11::decay_t<integers>>(ends_r)));
  END_CPP11
}
// cpp11bigwig.cpp
writable::list read_bigbed_cpp(std::string bbfname, strings chroms_r, integers starts_r, integers ends_r);
extern "C" SEXP _cpp11bigwig_read_bigbed_cpp(SEXP bbfname, SEXP chroms_r, SEXP starts_r, SEXP ends_r) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_bigbed_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(bbfname), cpp11::as_cpp<cpp11::decay_t<strings>>(chroms_r), cpp11::as_cpp<cpp11::decay_t<integers>>(starts_r), cpp11::as_cpp<cpp11::decay_t<integers>>(ends_r)));
  END_CPP11
}
// cpp11bigwig.cpp
std::string bigbed_sql_cpp(std::string bbfname);
extern "C" SEXP _cpp11bigwig_bigbed_sql_cpp(SEXP bbfname) {
  BEGIN_CPP11
    return cpp11::as_sexp(bigbed_sql_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(bbfname)));
  END_CPP11
}
// cpp11bigwig.cpp
writable::list bigbed_info_cpp(std::string bbfname);
extern "C" SEXP _cpp11bigwig_bigbed_info_cpp(SEXP bbfname) {
  BEGIN_CPP11
    return cpp11::as_sexp(bigbed_info_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(bbfname)));
  END_CPP11
}
// cpp11bigwig.cpp
writable::list bigwig_info_cpp(std::string bwfname);
extern "C" SEXP _cpp11bigwig_bigwig_info_cpp(SEXP bwfname) {
  BEGIN_CPP11
    return cpp11::as_sexp(bigwig_info_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(bwfname)));
  END_CPP11
}
// cpp11bigwig.cpp
bool bigwig_has_curl_cpp();
extern "C" SEXP _cpp11bigwig_bigwig_has_curl_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(bigwig_has_curl_cpp());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp11bigwig_bigbed_info_cpp",     (DL_FUNC) &_cpp11bigwig_bigbed_info_cpp,     1},
    {"_cpp11bigwig_bigbed_sql_cpp",      (DL_FUNC) &_cpp11bigwig_bigbed_sql_cpp,      1},
    {"_cpp11bigwig_bigwig_has_curl_cpp", (DL_FUNC) &_cpp11bigwig_bigwig_has_curl_cpp, 0},
    {"_cpp11bigwig_bigwig_info_cpp",     (DL_FUNC) &_cpp11bigwig_bigwig_info_cpp,     1},
    {"_cpp11bigwig_read_bigbed_cpp",     (DL_FUNC) &_cpp11bigwig_read_bigbed_cpp,     4},
    {"_cpp11bigwig_read_bigwig_cpp",     (DL_FUNC) &_cpp11bigwig_read_bigwig_cpp,     4},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp11bigwig(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
