// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_bigwig_impl
DataFrame read_bigwig_impl(std::string bwfname, std::string chrom, int start, int end);
RcppExport SEXP bigwrig_read_bigwig_impl(SEXP bwfnameSEXP, SEXP chromSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type bwfname(bwfnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type chrom(chromSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    __result = Rcpp::wrap(read_bigwig_impl(bwfname, chrom, start, end));
    return __result;
END_RCPP
}
