# Generated by cpp11: do not edit by hand

read_bigwig_cpp <- function(bwfname, chroms_r, starts_r, ends_r) {
  .Call(`_cpp11bigwig_read_bigwig_cpp`, bwfname, chroms_r, starts_r, ends_r)
}

read_bigbed_cpp <- function(bbfname, chroms_r, starts_r, ends_r) {
  .Call(`_cpp11bigwig_read_bigbed_cpp`, bbfname, chroms_r, starts_r, ends_r)
}

bigbed_sql_cpp <- function(bbfname) {
  .Call(`_cpp11bigwig_bigbed_sql_cpp`, bbfname)
}

bigbed_info_cpp <- function(bbfname) {
  .Call(`_cpp11bigwig_bigbed_info_cpp`, bbfname)
}

bigwig_info_cpp <- function(bwfname) {
  .Call(`_cpp11bigwig_bigwig_info_cpp`, bwfname)
}

bigwig_has_curl_cpp <- function() {
  .Call(`_cpp11bigwig_bigwig_has_curl_cpp`)
}
