# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_bigwig_impl <- function(bwfname, chrom, start, end) {
    .Call('bigwrig_read_bigwig_impl', PACKAGE = 'bigwrig', bwfname, chrom, start, end)
}

