# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_bigwig_impl <- function(bwfname, chrom, start, end) {
    .Call('_bigwig_read_bigwig_impl', PACKAGE = 'bigwig', bwfname, chrom, start, end)
}

